routingMode: "tunnel"
autoDirectNodeRoutes: false

kubeProxyReplacement: true
enableHostReachableServices: true

bpf:
  masquerade: true

nodePort:
  enabled: true

hubble:
  relay:
    enabled: true
  ui:
    enabled: true
    baseUrl: "/"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-issuer
      className: "cilium"
      hosts:
        - "hubble.k8s-lab.local"
      tls:
        - hosts:
          - "hubble.k8s-lab.local"
          secretName: hubble-ui-tls
    service:
      type: "ClusterIP"

ingressController:
  enabled: true
  default: true
  enforceHttps: false
  loadbalancerMode: "shared"
  service:
    type: NodePort
    insecureNodePort: 30080
    secureNodePort: 30443



