app:
  tls:
    rootCAFile: "/var/run/secrets/istio-csr/root-cert.pem"
  server: 
    caTrustedNodeAccounts: "istio-system/ztunnel"
  certmanager:
    issuer:
      group: cert-manager.io
      kind: ClusterIssuer
      name: istio-ca-issuer

volumeMounts:
  - name: "root-ca"
    mountPath: "/var/run/secrets/istio-csr"

volumes: 
  - name: root-ca
    configMap: 
      name: "istio-root-ca-bundle"