envoy:
  enabled: true
  mode: embedded

  extraVolumes:
  - name: trusted-ca
    secret:
      secretName: k8s-lab-ca-secret
  
  extraVolumeMounts:
  - name: trusted-ca
    mountPath: /etc/ssl/certs/ca-bundle.crt
    subPath: cert.pem
    readOnly: true
    
  extraEnv:
  - name: SSL_CERT_FILE
    value: /etc/ssl/certs/ca-bundle.crt