routingMode: "tunnel"
autoDirectNodeRoutes: false

kubeProxyReplacement: true
enableHostReachableServices: true

cni:
  exclusive: false

bpf:
  masquerade: false

socketLB:
  hostNamespaceOnly: true

nodePort:
  enabled: true

gatewayAPI:
  enabled: false

ingressController:
  enabled: false
  default: true
  enforceHttps: false
  loadbalancerMode: "shared"
  service:
    type: NodePort
    insecureNodePort: 30080
    secureNodePort: 30443



