autoDirectNodeRoutes: false

kubeProxyReplacement: true
enableHostReachableServices: true

cni:
  exclusive: false

bpf:
  masquerade: false

socketLB:
  hostNamespaceOnly: true

nodePort:
  enabled: true

gatewayAPI:
  enabled: false

envoy:
  enabled: false
loadBalancer:
  l7:
    backend: disabled

ingressController:
  enabled: false


