ipam:
  mode: "kubernetes"
  operator:
    clusterPoolIPv4PodCIDRList:
      - "10.96.0.0/12"

l2announcements:
  enabled: true

kubeProxyReplacement: true
k8sServiceHost: "minikube"
k8sServicePort: 8443