ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDRList: ["10.244.0.0/16"]

routingMode: "native"
ipv4NativeRoutingCIDR: "10.244.0.0/16"
autoDirectNodeRoutes: true

kubeProxyReplacement: true

loadBalancer:
  l2announcements:
    enabled: true

enableExternalIPs: true

bpf:
  masquerade: true

  ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4MaskSize: 24
    clusterPoolIPv4PodCIDRList:
      - "10.244.0.0/16"