routingMode: "tunnel"
autoDirectNodeRoutes: false

kubeProxyReplacement: true
enableHostReachableServices: true

bpf:
  masquerade: true

nodePort:
  enabled: true

hubble:
  relay:
    enabled: true
  ui:
    enabled: true
    baseUrl: "/hubble"
    ingress:
      enabled: true
      annotations:
        ingress.cilium.io/force-https: disabled
        ingress.cilium.io/protocol: http/1.1
      className: "cilium"
      hosts:
        - "minikube.local"
    service:
      type: "ClusterIP"

ingressController:
  enabled: true
  default: true
  enforceHttps: false
  loadbalancerMode: "shared"
  service:
    type: NodePort
    insecureNodePort: 30080
    secureNodePort: 30443



