ingressController:
  enabled: true
  loadbalancerMode: "dedicated"

hubble:
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      className: "cilium"
      hosts:
      - "localhost"
      path: "/hubble"